### ISSUE TITLE
io_uring_enter EINTR handling

### ISSUE THREAD

**Issue by tmds** [tkp1n/IoUring#29]
`io_uring_enter` can return `EINTR`, and when it does, it should be called again.

```
IoUring.ErrnoException: Interrupted system call
   at IoUring.Internal.ThrowHelper.ThrowErrnoException()
   at IoUring.Internal.SubmissionQueue.Flush(Int32 ringFd, Boolean kernelIoPolling, UInt32 toFlush, UInt32 minComplete)
   at IoUring.Ring.Flush(UInt32 toFlush, UInt32 minComplete)
```

**Comment by tkp1n** [comment]
Relates to #27 

I suggest to call it again inside the `Flush` method and stop throwing exceptions for this errno. Do you agree with this approach?

**Comment by tkp1n** [comment]
Strange that `EINTR` isn't documented as possible error case for `io_uring_enter`
https://github.com/axboe/liburing/blob/master/man/io_uring_enter.2

\cc @axboe
